language: python
python:
   - 2.7
   - 3.4
virtualenv:
    system_site_packages: true
before_install:
   - sudo apt-get install -qq python3-numpy python3-scipy python-numpy python-scipy libblas3
   - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
   - chmod +x miniconda.sh
   - ./miniconda.sh -b
   - export PATH=/home/travis/miniconda/bin:$PATH
   - conda update --yes conda   
env:
   - TOX_ENV=py27
   - TOX_ENV=pytest
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy nose dateutil pandas statsmodels
  - python setup.py install
  - pip install mercurial tox 
script: tox -e $TOX_ENV