language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
install: 
  - "pip install -r requirements-test-py27.txt"
  - "pip install -r requirements.txt"
  - python setup.py install

before_install:
  - sudo apt-get install -qq python-numpy

script: py.test tests/
