language: python
python:
   - "2.7"
   - "3.4"
virtualenv:
   - "2.7_with_system_site_packages"
   - "3.4_with_system_site_packages"    
before_install:
   - sudo apt-get install -qq python3-numpy python3-scipy python-numpy python-scipy
install:
  - python setup.py install
script: py.test tests/
