language: python
python:
  - "2.7_with_system_site_packages"
  - "3.4_with_system_site_packages"

install: 
  - "pip install -r requirements.txt"
  - python setup.py install

before_install:
  - sudo apt-get install -qq python3-numpy python3-scipy python-numpy python-scipy

script: py.test tests/
