language: python
python:
   - 2.7
virtualenv:
    system_site_packages: true
before_install:
   - sudo apt-get install -qq python3-numpy python3-scipy python-numpy python-scipy
env:
   - TOX_ENV=py27
   - TOX_ENV=pytest
install:
   - pip install mercurial tox
script: tox -e $TOX_ENV
